# Generated by Django 3.1 on 2020-08-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacypolicy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
